// FILE SINH TỰ ĐỘNG bởi tools/build-catalog.mjs — KHÔNG sửa tay.
// Bảng tiêu đề ngắn của bài để resolveRefs() thay [[lesson:slug]] đồng bộ (không cần fetch).
export const LESSON_TITLES = {
  "activation_checkpointing": "Activation Checkpointing",
  "activation_valves": "Van Kích Hoạt & Lời Nguyền Trọng Số 0",
  "adamw_weight_decay": "Weight Decay",
  "autograd_graph": "Đồ Thị Tính Toán DAG & Sóng Dội Ngược",
  "batch_norm_dynamics": "Ổn Định Nội Bộ Với BatchNorm",
  "broadcast_grad": "Gradient Của Broadcast (Cộng dồn)",
  "cache_locality": "Row-Major vs Col-Major Cache Locality",
  "coalescing_and_banks": "Memory Coalescing & Bank Conflicts",
  "conv2d_im2col": "Conv2D & Thần Chú Im2col",
  "cpp_matmul_loops": "Dò Tay Vòng Lặp Nhân Ma Trận C++",
  "cross_entropy_logsumexp": "Cross-Entropy dạng Log-Sum-Exp",
  "cuda_threads": "Phân Cấp Luồng CUDA Grid, Blocks & Threads",
  "data_parallel_allreduce": "Data Parallel & All-Reduce",
  "dropout": "Dropout",
  "embedding_tokenization": "Tokenization (BPE) & Embedding",
  "flash_attention": "FlashAttention SRAM Tiling & Online Softmax",
  "gqa_kv_cache": "GQA / MQA",
  "gradient_accumulation_clipping": "Gradient Accumulation & Clipping",
  "gradient_check": "Kiểm Tra Gradient Bằng Số (Gradient Check)",
  "kaiming_init": "Khởi Tạo Kaiming",
  "kv_cache_anatomy": "Giải Phẫu KV-Cache Trong LLM Serving",
  "layernorm_residual": "LayerNorm & Residual",
  "lora_finetuning": "LoRA",
  "lr_schedule_warmup": "LR Schedule",
  "memory_leak": "Robot Chết Đuối Vì Memory Leak",
  "minibatch_assembly": "Băng Chuyền Mini-Batching Assembly Line",
  "minibatch_sgd": "Xử Lý Mini-batch $B=2$ & Phép Chuyển Vị $X^T$",
  "mixed_precision": "Mixed Precision",
  "moe_routing": "Mixture-of-Experts",
  "multi_head_attention": "Multi-Head Attention",
  "optimizers": "Động Học Các Bộ Tối Ưu",
  "overfitting_validation": "Overfitting & Validation",
  "positional_encoding": "Positional Encoding",
  "quantization_int8": "Quantization INT8/INT4",
  "reverse_vs_forward_ad": "Reverse-mode vs Forward-mode AD",
  "rnn_bptt": "RNN & BPTT",
  "robot_vision": "Robot Vision & Tích Vô Hướng Vector",
  "roofline_arithmetic_intensity": "Roofline",
  "rope_rotary": "RoPE",
  "sampling_decoding": "Sampling & Decoding",
  "self_attention": "Scaled Dot-Product Self-Attention",
  "shared_memory_tiling": "Tiled MatMul & Shared Memory",
  "softmax_regression": "Chu Trình Softmax Regression (Ma trận)",
  "softmax_stability": "Softmax & Cơn Ác Mộng Lóa Sáng",
  "strides_views": "Strides & View",
  "transformer_block_params": "Khối Transformer Hoàn Chỉnh",
  "twolayer_relu_backprop": "Mạng Nơ-ron 2 Tầng & Lan Truyền Ngược ReLU",
  "zero_fsdp": "ZeRO / FSDP"
};
